ai_takatta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

app_name = 'app'
urlpatterns = [
	path('', landing, name='landing'),
	path('game', game, name='game'),
	path('soal', soal, name='soal'),
	path('hasil', hasil, name='hasil'),
]

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from .forms import *
from .models import *
from .dataconstructor import *
from django.views.decorators.csrf import csrf_exempt

from collections import defaultdict, Counter
import itertools
import math
import csv
import random

response = {}

T = bool(True)
F = bool(False)

def landing(request):
    html = 'landing.html'
    # decide()
    return render(request, html)

def game(request):
    html = 'game.html'
    return render(request, html)

def soal(request):
    html = 'soal.html'
    return render(request, html)

@csrf_exempt
def hasil(request):
    # bikin logic nya disini aja
    net = (BayesNet()
    .add('a1',[], 0.1)
    .add('a2',[], 0.1)
    .add('a3',[], 0.1)
    .add('a4',[], 0.1)
    .add('a5',[], 0.1)
    .add('a6',[], 0.1)
    )

    dct = {}
    with open('app/static/data/dataset.csv') as csvfile:
        readCSV = csv.reader(csvfile, delimiter=',')
        for row in readCSV:
            tmp = []
	        # print(row)
            if(row[0][0]=='Q'):
                continue
            for i in range(len(row)):
                if(row[i][0]=='T'):
                    tmp.append(T)
                elif i>5:
                    tmp.append(row[i])
                else:
                    tmp.append(F)
            key = (tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5])
	        # print(key)
            dct[key]= float(tmp[12])
	        # print (dct)

	# print(dct)
    net.add('a7', ['a1','a2','a3','a4','a5','a6'], dct)
    
    globalize(net.lookup) 

    bayesNetwork = generateBayesNetwork()
    answer = dict(request.POST)
    val1 = getData(answer.__getitem__('1'))
    val2 = getData(answer.__getitem__('2'))
    val3 = getData(answer.__getitem__('3'))
    val4 = getData(answer.__getitem__('4'))
    val5 = getData(answer.__getitem__('5'))
    val6 = getData(answer.__getitem__('6'))

    dataInput = {a1:val1, a2:val2, a3:val3, a4:val4,  a5:val5, a6:val6}
    dataResult = {key: value for key, value in dataInput.items() if value is not None}
    bayesValue = enumeration_ask(a7, dataResult, net)[T] * 100
    print(dataResult)
    print(enumeration_ask(a7, {a1:F, a2:F, a3:F, a4:F, a5:F, a6:F}, net)[T]*100)
    response['test'] = float("{0:.2f}".format(bayesValue))

    html = 'hasil.html'
    return render(request, html, response)



def getData(object):
	if object == ['Iya']:
		return T
	elif object == ['Tidak']:
		return F
	else:
		return

class BayesNet(object):
    "Bayesian network: a graph of variables connected by parent links."
     
    def __init__(self): 
        self.variables = [] # List of variables, in parent-first topological sort order
        self.lookup = {}    # Mapping of {variable_name: variable} pairs
            
    def add(self, name, parentnames, cpt):
        "Add a new Variable to the BayesNet. Parentnames must have been added previously."
        parents = [self.lookup[name] for name in parentnames]
        var = Variable(name, cpt, parents)
        self.variables.append(var)
        self.lookup[name] = var
        return self
    
class Variable(object):
    "A discrete random variable; conditional on zero or more parent Variables."
    
    def __init__(self, name, cpt, parents=()):
        "A variable has a name, list of parent variables, and a Conditional Probability Table."
        self.__name__ = name
        self.parents  = parents
        self.cpt      = CPTable(cpt, parents)
        self.domain   = set(itertools.chain(*self.cpt.values())) # All the outcomes in the CPT
                
    def __repr__(self): return self.__name__
    
class Factor(dict): "An {outcome: frequency} mapping."

class ProbDist(Factor):
    """A Probability Distribution is an {outcome: probability} mapping. 
    The values are normalized to sum to 1.
    ProbDist(0.75) is an abbreviation for ProbDist({T: 0.75, F: 0.25})."""
    def __init__(self, mapping=(), **kwargs):
        if isinstance(mapping, float):
            mapping = {T: mapping, F: 1 - mapping}
        self.update(mapping, **kwargs)
        normalize(self)
        
class Evidence(dict): 
    "A {variable: value} mapping, describing what we know for sure."
        
class CPTable(dict):
    "A mapping of {row: ProbDist, ...} where each row is a tuple of values of the parent variables."
    
    def __init__(self, mapping, parents=()):
        """Provides two shortcuts for writing a Conditional Probability Table. 
        With no parents, CPTable(dist) means CPTable({(): dist}).
        With one parent, CPTable({val: dist,...}) means CPTable({(val,): dist,...})."""
        if len(parents) == 0 and not (isinstance(mapping, dict) and set(mapping.keys()) == {()}):
            mapping = {(): mapping}
        for (row, dist) in mapping.items():
            if len(parents) == 1 and not isinstance(row, tuple): 
                row = (row,)
            self[row] = ProbDist(dist)

class Bool(int):
    "Just like `bool`, except values display as 'T' and 'F' instead of 'True' and 'False'"
    __str__ = __repr__ = lambda self: 'T' if self else 'F'
def P(var, evidence={}):
    "The probability distribution for P(variable | evidence), when all parent variables are known (in evidence)."
    row = tuple(evidence[parent] for parent in var.parents)
    return var.cpt[row]

def normalize(dist):
    "Normalize a {key: value} distribution so values sum to 1.0. Mutates dist and returns it."
    total = sum(dist.values())
    for key in dist:
        dist[key] = dist[key] / total
        assert 0 <= dist[key] <= 1, "Probabilities must be between 0 and 1."
    return dist

def sample(probdist):
    "Randomly sample an outcome from a probability distribution."
    r = random.random() # r is a random point in the probability distribution
    c = 0.0             # c is the cumulative probability of outcomes seen so far
    for outcome in probdist:
        c += probdist[outcome]
        if r <= c:
            return outcome
        
def globalize(mapping):
    "Given a {name: value} mapping, export all the names to the `globals()` namespace."
    globals().update(mapping)

def joint_distribution(net):
    "Given a Bayes net, create the joint distribution over all variables."
    return ProbDist({row: prod(P_xi_given_parents(var, row, net)
                               for var in net.variables)
                     for row in all_rows(net)})

def all_rows(net): return itertools.product(*[var.domain for var in net.variables])

def P_xi_given_parents(var, row, net):
    "The probability that var = xi, given the values in this row."
    dist = P(var, Evidence(zip(net.variables, row)))
    xi = row[net.variables.index(var)]
    return dist[xi]

def prod(numbers):
    "The product of numbers: prod([2, 3, 5]) == 30. Analogous to `sum([2, 3, 5]) == 10`."
    result = 1
    for x in numbers:
        result *= x
    return result

def enumeration_ask(X, evidence, net):
    "The probability distribution for query variable X in a belief net, given evidence."
    i    = net.variables.index(X) # The index of the query variable X in the row
    dist = defaultdict(float)     # The resulting probability distribution over X
    for (row, p) in joint_distribution(net).items():
        if matches_evidence(row, evidence, net):
            dist[row[i]] += p
    return ProbDist(dist)

def matches_evidence(row, evidence, net):
    "Does the tuple of values for this row agree with the evidence?"
    return all(evidence[v] == row[net.variables.index(v)]
               for v in evidence)

app/templates/game.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Stress Detector Quiz</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
        <div id="home" class="flex-center flex-column">
            <h1 style="text-align: center">Stress Detector Quiz</h1>
            <a class="btn" href="{% url 'app:soal' %}">Play</a>
            <a class="btn" href="{% url 'app:landing' %}">About Me</a>
        </div>
        </div>
    </body>
</html>

app/templates/hasil.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Result</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    </head>
    <body>
        <div class="container">
            <div id="end" class="flex-center flex-column text-center">
                <h1 id="hasil">Your Result</h1>
                <h2 class="question-text">Kemungkinan tingkat stress anda adalah: {{ test }}%</h2>
                <a class="btn" href="{% url 'app:soal' %}">Play Again</a>
                <a class="btn" href="{% url 'app:landing' %}">Go Home</a>
            </div>
        </div>
    </body>
</html>

app/templates/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Stress Detector Quiz</title>
    
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'css/landing.css' %}">
    
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <!-- Start About Area -->
	<section class="about-area section-gap">
            <div class="container">
                <div class="row align-items-center justify-content-between">
                    <div class="col-lg-6 about-left">
                        <iframe width="520" height="360" src="https://www.youtube.com/embed/BYwq2l63I14">
                        </iframe>
                    </div>
                    <div class="col-lg-5 col-md-12 about-right">
                        <div class="section-title">
                            <h2>about project</h2>
                        </div>
                        <div class="mb-50 wow fadeIn" data-wow-duration=".8s">
                            <p>
                                Kuis ini adalah Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                            </p>
                            <p>That’s why it’s crucial that, as women, our behavior on the job is beyond reproach. inappropriate behavior is often
                                laughed.
                            </p>
                        </div>
                        <a class="btn" href="{% url 'app:game' %}">Play</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- End About Area -->
        <section class="team-area section-gap" id="team">
            <div class="container">
                <div class="row d-flex justify-content-between align-items-end mb-80">
                    <div class="col-lg-6">
                        <div class="section-title">
                            <h2>Our Team</h2>
                            <p>Tim kami terdiri dari 4 orang yang sedang belajar AI "for humanity"</p>
                        </div>
                    </div>
                </div>
    
                <div class="filters-content">
                    <div class="row grid">
                        <div class="team col-lg-3 col-md-6 col-sm-6 all creative wow fadeInUp" data-wow-duration="2s">
                            <div class="relative">
                                <div class="thumb">
                                    <div class="overlay overlay-bg"></div>
                                    <img class="image img-fluid" src="https://media.licdn.com/dms/image/C5603AQG7Gk3BcZlcPg/profile-displayphoto-shrink_800_800/0?e=1580947200&v=beta&t=bQq7KjLB3dS-GimEgVzDfgmYEj_4kg6h4dVS9oC4bU4" alt="">
                                </div>
                                <div class="middle">
                                    <h4>Dhipta Raditya</h4>
                                    <div class="cat">AI Engineer</div>
                                </div>
                                <a class="overlay" href="https://www.linkedin.com/in/dhipta-raditya-9a1bb6152/"></a>
                            </div>
                        </div>
    
                        <div class="team col-lg-3 col-md-6 col-sm-6 all web-design branding wow fadeInUp" data-wow-duration="2s" data-wow-delay="0.2s">
                            <div class="relative">
                                <div class="thumb">
                                    <div class="overlay overlay-bg"></div>
                                    <img class="image" src="https://media.licdn.com/dms/image/C5103AQESBLuuWNHN5g/profile-displayphoto-shrink_800_800/0?e=1580947200&v=beta&t=w3PGo6tEiUHWeOClZH1BLDRRXpYxdbNoRGp6iWYPL8Y" alt="">
                                </div>
                                <div class="middle">
                                    <h4>Usman Sidiq</h4>
                                    <div class="cat">AI Engineer</div>
                                </div>
                                <a class="overlay" href="https://www.linkedin.com/in/usman-sidiq/"></a>
                            </div>
                        </div>

                        <div class="team col-lg-3 col-md-6 col-sm-6 all branding web-design wow fadeInUp" data-wow-duration="2s" data-wow-delay="0.4s">
                            <div class="relative">
                                <div class="thumb">
                                    <div class="overlay overlay-bg"></div>
                                    <img class="image img-fluid" src="https://media.licdn.com/dms/image/C5103AQFtrJfPh068Wg/profile-displayphoto-shrink_200_200/0?e=1580947200&v=beta&t=TBtNU2Ysc4VpPvoMmYE-5wdL61AMT8yefoI2CEc62sg" alt="">
                                </div>
                                <div class="middle">
                                    <h4>Razaqa Dhafin</h4>
                                    <div class="cat">Back-End Engineer</div>
                                </div>
                                <a class="overlay" href="https://www.linkedin.com/in/razaqa-dhafin/"></a>
                            </div>
                        </div>
    
                        <div class="team col-lg-3 col-md-6 col-sm-6 all web-design wow fadeInUp" data-wow-duration="2s" data-wow-delay="0.6s">
                            <div class="relative">
                                <div class="thumb">
                                    <div class="overlay overlay-bg"></div>
                                    <img class="image img-fluid" src="https://i.ibb.co/yRHjTcF/10527555-867558336590301-4976539022065500227-n.jpg" alt="">
                                </div>
                                <div class="middle">
                                    <h4>Irfan Aziz</h4>
                                    <div class="cat">Front-End Engineer</div>
                                </div>
                                <a class="overlay" href="https://www.linkedin.com/in/irfan-aziz-al-amin-16967b142/"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    
        <section class="service-area section-gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-title">
                            <h2>Stress Level</h2>
                            <p>Dibawah merupakan level kesetresan dalam quiz ini yang 
                            menunjukkan tingkat kesetresan anda</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="service wow fadeInUp" data-wow-duration="1s">
                            <h4>
                                <span>Tidak</span> Stress
                            </h4>
                            <p>Anda dinyatakan tidak stress jika presentase hasil quiz anda dibawah <b>30</b></p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="service wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.2s">
                            <h4>
                                <span>Sedikit</span> Stress
                            </h4>
                            <p>Anda dinyatakan tidak stress jika presentase hasil quiz anda diantara <b>50</b> dan <b>70</b></p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="service wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.4s">
                            <h4>
                                <span>Lumayan</span> Stress
                            </h4>
                            <p>Anda dinyatakan tidak stress jika presentase hasil quiz anda diantara <b>70</b> dan <b>90</b></p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="service wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.6s">
                            <h4>
                                <span>Sangat</span> Stress
                            </h4>
                            <p>Anda dinyatakan tidak stress jika presentase hasil quiz anda diatas <b>90</b></p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    
        <div id="back-top">
            <a title="Go to Top" href="#">
                <i class="lnr lnr-arrow-up"></i>
            </a>
        </div>
    
        <!-- start footer Area -->
        <footer class="footer-area">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="footer-top flex-column">
                            <div class="footer-logo">	
                                <h4>Follow Us</h4>
                            </div>
                            <div class="footer-social">
                                <a href="https://gitlab.com/dhafins18/sistem_cerdas_ai_takatta.git"><i class="fa fa-gitlab"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row footer-bottom justify-content-center">
                    <p class="col-lg-8 col-sm-12 footer-text">
    Copyright &copy; All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://gitlab.com/dhafins18/sistem_cerdas_ai_takatta.git">us</a>
                </div>
            </div>
        </footer>
        <!-- End footer Area -->
</body>
</html>

app/templates/soal.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Quiz - Play</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">        
        <link rel="stylesheet" type="text/css" href="{% static 'css/soal.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdn.rawgit.com/mgalante/jquery.redirect/master/jquery.redirect.js"></script>

        <script>
            $(document).ready(function(){
                var selected_answer = {}
                const progressText = document.getElementById("progressText");
                const progressBarFull = document.getElementById("progressBarFull");
                const loader = document.getElementById("loader");
                
                function Quiz(questions) {
                    this.questions = questions;
                    this.questionIndex = 0;
                }

                Quiz.prototype.getQuestionIndex = function() {
                    return this.questions[this.questionIndex];
                }

                Quiz.prototype.isEnded = function() {
                    return this.questionIndex === this.questions.length;
                }

                Quiz.prototype.update = function() {
                    this.questionIndex++;
                }

                showQuestion();
                game.classList.remove("hidden");
                loader.classList.add("hidden");

                function showQuestion() {
                    $.getJSON("{% static 'data/soal.json' %}", function(datas) {
                        var quiz = new Quiz(datas.questions);
                        const MAX_QUESTIONS = quiz.questions.length;
                        let questionCounter = 0;

                        populate();

                        function populate() {
                            if(quiz.isEnded()) {
                                game.classList.add("hidden");
                                loader.classList.remove("hidden");
                                $.redirect("{% url 'app:hasil' %}", selected_answer, "POST"); 
                            }
                            else {
                                progressBarFull.style.width = `${(questionCounter / MAX_QUESTIONS) * 100}%`;
                                progressText.innerText = `Question ${questionCounter+1}/${MAX_QUESTIONS}`;

                                // show question
                                $('.questions').append('<h2 class="question-text">' + quiz.getQuestionIndex().question + '</h2>');

                                // show options
                                var options = quiz.getQuestionIndex().answers;
                                for(var i = 0; i < options.length; i++) {
                                    $('.choices').append('<div class="choice-container"><p class="choice-prefix">' + String.fromCharCode(i+65) + '</p><p class="choice-text" data-number="' + (i+1) + '">' + options[i] + '</p></div>');
                                }
                                
                                const choices = Array.from($('.choice-text'));
                                choices.forEach(choice => {
                                    choice.addEventListener("click", e => {
                                        selected_answer[questionCounter + 1] = choice.innerHTML

                                        console.log(selected_answer)
                                        $("div.choice-container").remove()
                                        $("h2.question-text").remove()

                                        quiz.update();
                                        questionCounter++;

                                        populate();
                                    })
                                });
                            }
                        }
                    });
                }
            });
        </script>
    </head>
    <body>
        <div class="container">
        <div id="loader"></div>
            <div id="game" class="justify-center flex-column hidden">
                <div id="hud">
                    <div id="hud-item">
                        <p id="progressText" class="hud-prefix">
                        Question
                        </p>
                        <div id="progressBar">
                        <div id="progressBarFull"></div>
                        </div>
                    </div>
                </div>
                <br><br><br>
                <div class="questions">
                </div>
                <div class="choices">
                </div>
            </div>
        </div>
    </body>
</html>